#!/usr/bin/env Rscript
library("irace")
setwd("/home/fye/MLGA/configurablega/main/irace-GA/DiffBudgetLO/ConfigureWithLinearECDF-Problem-IRACE/")
scenario <- readScenario(filename = "instance/problem_id-scenario.txt",scenario = defaultScenario())
irace.main(scenario = scenario)
